---
title: "20180130 Analysing reactive amines on GrNH2"
bibliography: misc/library.bib
csl: misc/csl/american-chemical-society-with-titles-doi-no-et-al.csl
---

```{r, child="_setup.Rmd"}
```

Since the Gr-NH~2~ produced in [20180119](20180119_GrNH2_mass_production.html) will be used in polyurethane synthesis, it is important to know how many amine-functionalitities are available for reaction. To test this we try to react the graphene with 3-(Trifluoromethyl)phenyl isocyanate. This should allow an easy detection of active amines through the fluorine signal in XPS.

The method was devised by combining input from several references.[@Oneill2011; @Wang2015a; @SCHMITT2013532]

# Journal

1. 3 mg graphene (20180119 2A) was ultrasonicated in THF for 30 min to disperse it
2. 0.05 mL 3-(Trifluoromethyl)phenyl isocyanate was added and the solution was stirred for 3 hr at room temperature.
3. The graphene was filtered 0.45 um nylon membrane filter and washed with THF and ethyl acetate. It was then dried overnight at room temperature.
4. XPS analysis should be conducted. 


# Results and discussion

# Conclusion and outlook
