theme: jekyll-theme-minimal
title: Graphene production for polymer composites
description: Production and functionalisation of graphene under the SPOMAN Open Science collaboration
show_downloads: true
