---
title: 'Lab Journal: Production of functionalised graphene'
author: "Emil Tveden Bjerglund"
date: "Last updated: `r Sys.Date()`"
csl: misc/csl/american-chemical-society-with-titles-doi-no-et-al.csl
output:
  rmdformats::html_clean:
    highlight: kate
    fig_width: 8
    fig_height: 3
    code_folding: hide
    md_extensions: +header_attributes
  pdf_document:
    toc: yes
    toc_depth: '1'
    fig_width: 8
    fig_height: 3
  word_document: default
bibliography: misc/library.bib
---

```{r setup, include=FALSE}
library(knitr)
library(rmdformats)
library(tidyverse)
library(units)

## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=FALSE,
               prompt=FALSE,
               tidy=FALSE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
opts_chunk$set(echo = TRUE)

rmd <- rev(list.files(pattern = '*.Rmd',path = 'lab_journal', recursive = TRUE, include.dirs = TRUE))
chunks <- paste0("```{r child = 'lab_journal/", rmd, "'}\n```\n")
readr::write_lines(chunks, "includes.Rmd")

```

```{r child = 'includes.Rmd'}
```

```{r cleanup, include=FALSE}
file.remove("includes.Rmd")
```
# References